//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_Zay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_HD
    {
        public int MaHD { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int TongTien { get; set; }
        public int MaCT { get; set; }
        public Nullable<int> Size { get; set; }
    
        public virtual Hoa_Don Hoa_Don { get; set; }
        public virtual San_Pham San_Pham { get; set; }
    }
}
