//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_Zay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoa_Don
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoa_Don()
        {
            this.Chi_Tiet_HD = new HashSet<Chi_Tiet_HD>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string TenNN { get; set; }
        public string DiaChiNN { get; set; }
        public string DienThoaiNN { get; set; }
        public string EmailNN { get; set; }
        public string GioiTinhNN { get; set; }
        public string GhiChuNN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_HD> Chi_Tiet_HD { get; set; }
        public virtual Khach_Hang Khach_Hang { get; set; }
    }
}
